"""empty message

Revision ID: 2d25d462c63d
Revises: 4befd9b27268
Create Date: 2023-05-21 00:52:25.870346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d25d462c63d'
down_revision = '4befd9b27268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_index('ix_userinfo_dob')

    op.drop_table('userinfo')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_dob'), ['dob'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dob'))
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('dob')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('userinfo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('dob', sa.DATETIME(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=64), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.create_index('ix_userinfo_dob', ['dob'], unique=False)

    # ### end Alembic commands ###
