"""empty message

Revision ID: b2927a1054bd
Revises: 2d25d462c63d
Create Date: 2023-05-22 18:49:37.533463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2927a1054bd'
down_revision = '2d25d462c63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
